/** Unit tests for canonical Gutenberg block examples. */

/**
 * Load the ability in an isolated module registry.
 *
 * @return {Object} Module exports.
 */
function loadModule() {
	let mod;
	jest.isolateModules( () => {
		// eslint-disable-next-line global-require
		mod = require( '../block-examples' );
	} );
	return mod;
}

/**
 * Set a minimal Gutenberg block API.
 *
 * @param {Object<string, Object>} blocks Registered blocks keyed by name.
 */
function setBlocks( blocks = {} ) {
	global.wp = {
		blocks: {
			getBlockType: jest.fn( ( name ) => blocks[ name ] || null ),
			createBlock: jest.fn( ( name, attributes, innerBlocks ) => ( {
				name,
				attributes,
				innerBlocks,
			} ) ),
			createBlocksFromInnerBlocksTemplate: jest.fn( ( template ) =>
				template.map(
					( [ name, attributes = {}, children = [] ] ) => ( {
						name,
						attributes,
						innerBlocks: children,
					} )
				)
			),
			serialize: jest.fn( ( values ) =>
				values
					.map(
						( value ) =>
							`<!-- wp:${ value.name } -->${
								value.attributes.content || ''
							}<!-- /wp:${ value.name } -->`
					)
					.join( '' )
			),
			parse: jest.fn( ( markup ) => {
				const match = markup.match( /<!-- wp:([^ ]+) -->/ );
				const content =
					markup.match( /-->(.*)<!-- \/wp:/ )?.[ 1 ] || '';
				return match
					? [
							{
								name: match[ 1 ],
								attributes: { content },
								innerBlocks: [],
							},
					  ]
					: [];
			} ),
			validateBlock: jest.fn( () => [ true, [] ] ),
		},
	};
}

describe( 'get-canonical-block-examples', () => {
	afterEach( () => {
		delete global.wp;
	} );

	test( 'returns a validated canonical example from registered metadata', () => {
		setBlocks( {
			'core/paragraph': {
				title: 'Paragraph',
				apiVersion: 3,
				save: jest.fn(),
				example: { attributes: { content: 'Example text' } },
			},
		} );
		const { getCanonicalBlockExamples } = loadModule();
		const result = getCanonicalBlockExamples( {
			blockNames: [ 'core/paragraph' ],
		} );

		expect( result.examples[ 0 ] ).toMatchObject( {
			block_name: 'core/paragraph',
			supported: true,
			source: 'registered-example',
			title: 'Paragraph',
			version: '3',
			valid: true,
		} );
		expect( result.examples[ 0 ].markup ).toContain( 'Example text' );
	} );

	test( 'uses a safe default only when the block has a save path', () => {
		setBlocks( {
			'plugin/default': { title: 'Default', save: jest.fn() },
		} );
		const { getCanonicalBlockExamples } = loadModule();
		const result = getCanonicalBlockExamples( {
			blockNames: [ 'plugin/default' ],
		} );

		expect( result.examples[ 0 ] ).toMatchObject( {
			supported: true,
			source: 'default-block',
		} );
	} );

	test( 'returns a validated third-party dynamic example when WordPress serializes it', () => {
		setBlocks( {
			'plugin/dynamic': {
				title: 'Plugin Dynamic',
				save: null,
				example: { attributes: {} },
			},
		} );
		const { getCanonicalBlockExamples } = loadModule();
		const result = getCanonicalBlockExamples( {
			blockNames: [ 'plugin/dynamic' ],
		} );

		expect( result.examples[ 0 ] ).toMatchObject( {
			block_name: 'plugin/dynamic',
			supported: true,
			source: 'registered-example',
		} );
	} );

	test( 'validates nested blocks generated by a registered example', () => {
		setBlocks( {
			'plugin/container': {
				save: jest.fn(),
				example: {
					attributes: {},
					innerBlocks: [ [ 'core/paragraph', { content: 'Child' } ] ],
				},
			},
			'core/paragraph': { save: jest.fn() },
		} );
		global.wp.blocks.parse.mockReturnValue( [
			{
				name: 'plugin/container',
				attributes: {},
				innerBlocks: [
					{ name: 'core/paragraph', attributes: {}, innerBlocks: [] },
				],
			},
		] );
		const { getCanonicalBlockExamples } = loadModule();
		const result = getCanonicalBlockExamples( {
			blockNames: [ 'plugin/container' ],
		} );

		expect( result.examples[ 0 ].supported ).toBe( true );
		expect( global.wp.blocks.validateBlock ).toHaveBeenCalledTimes( 2 );
	} );

	test( 'rejects missing, unsupported, and dynamic blocks without examples', () => {
		setBlocks( { 'plugin/dynamic': { title: 'Dynamic', save: null } } );
		const { getCanonicalBlockExamples } = loadModule();
		const result = getCanonicalBlockExamples( {
			blockNames: [ 'missing/block', 'core/freeform', 'plugin/dynamic' ],
		} );

		expect( result.examples.map( ( example ) => example.reason ) ).toEqual(
			[
				'unregistered_block',
				'unsupported_block_type',
				'missing_safe_default_save_path',
			]
		);
	} );

	test( 'rejects invalid round trips without returning fabricated markup', () => {
		setBlocks( { 'plugin/invalid': { save: jest.fn() } } );
		global.wp.blocks.validateBlock.mockReturnValue( {
			isValid: false,
			validationIssues: [ { message: 'Broken save output' } ],
		} );
		const { getCanonicalBlockExamples } = loadModule();
		const result = getCanonicalBlockExamples( {
			blockNames: [ 'plugin/invalid' ],
		} );

		expect( result.examples[ 0 ] ).toMatchObject( {
			supported: false,
			reason: 'invalid_round_trip',
			warnings: [ 'Broken save output' ],
		} );
		expect( result.examples[ 0 ].markup ).toBeUndefined();
	} );

	test( 'rejects duplicate and over-cap requests before generation', () => {
		setBlocks();
		const { getCanonicalBlockExamples, MAX_BLOCK_NAMES } = loadModule();
		expect(
			getCanonicalBlockExamples( {
				blockNames: [ 'core/paragraph', 'core/paragraph' ],
			} )
		).toMatchObject( {
			available: true,
			examples: [],
			warnings: [ 'block_names_must_contain_one_to_twenty_unique_names' ],
		} );
		expect(
			getCanonicalBlockExamples( {
				blockNames: Array.from(
					{ length: MAX_BLOCK_NAMES + 1 },
					( _, index ) => `plugin/${ index }`
				),
			} )
		).toMatchObject( { examples: [] } );
	} );

	test( 'rejects serialized markup over the per-block cap', () => {
		setBlocks( { 'plugin/large': { save: jest.fn() } } );
		const { MAX_BLOCK_MARKUP_BYTES, getCanonicalBlockExamples } =
			loadModule();
		global.wp.blocks.serialize.mockReturnValue(
			'x'.repeat( MAX_BLOCK_MARKUP_BYTES + 1 )
		);

		expect(
			getCanonicalBlockExamples( { blockNames: [ 'plugin/large' ] } )
		).toMatchObject( {
			examples: [ { supported: false, reason: 'block_markup_limit' } ],
		} );
	} );
} );
