<?php

declare(strict_types=1);
/**
 * Test case for ThemeBuilderAbilities (ScaffoldBlockThemeAbility + ActivateThemeAbility).
 *
 * Covers t226c subphase 3a (GH#1385): the two abilities that underpin the
 * theme-builder onboarding branch. Tests are structured around the WP_Error
 * branches each ability exposes so the AI agent gets a usable signal on
 * misuse, plus the happy-path scaffold-then-activate round-trip.
 *
 * @package SdAiAgent
 * @subpackage Tests
 * @license GPL-2.0-or-later
 */

namespace SdAiAgent\Tests\Abilities;

use SdAiAgent\Abilities\ActivateThemeAbility;
use SdAiAgent\Abilities\ScaffoldBlockThemeAbility;
use WP_UnitTestCase;

/**
 * Test ThemeBuilderAbilities functionality.
 */
class ThemeBuilderAbilitiesTest extends WP_UnitTestCase {

	/**
	 * Slugs created during tests, removed in tearDown.
	 *
	 * @var array<int,string>
	 */
	private array $created_slugs = [];

	/**
	 * Original active stylesheet, restored in tearDown.
	 *
	 * @var string
	 */
	private string $original_stylesheet = '';

	public function setUp(): void {
		parent::setUp();
		$this->original_stylesheet = (string) get_stylesheet();
	}

	public function tearDown(): void {
		// Restore the original stylesheet so other tests are not affected by
		// switch_theme() side effects from this test class.
		if ( '' !== $this->original_stylesheet
			&& $this->original_stylesheet !== get_stylesheet()
		) {
			switch_theme( $this->original_stylesheet );
		}

		foreach ( $this->created_slugs as $slug ) {
			$dir = trailingslashit( get_theme_root() ) . $slug;
			if ( is_dir( $dir ) ) {
				self::rrmdir( $dir );
			}
		}

		parent::tearDown();
	}

	// ── ScaffoldBlockThemeAbility ─────────────────────────────────────────

	/**
	 * ScaffoldBlockThemeAbility returns WP_Error when slug is missing.
	 */
	public function test_scaffold_returns_wp_error_for_missing_slug(): void {
		$ability = new ScaffoldBlockThemeAbility( 'sd-ai-agent/scaffold-block-theme' );

		$result = $ability->run( [ 'name' => 'My Theme' ] );

		$this->assertWPError( $result );
		$this->assertSame( 'sd_ai_agent_invalid_slug', $result->get_error_code() );
	}

	/**
	 * ScaffoldBlockThemeAbility rejects slugs with invalid characters.
	 */
	public function test_scaffold_returns_wp_error_for_invalid_slug(): void {
		$ability = new ScaffoldBlockThemeAbility( 'sd-ai-agent/scaffold-block-theme' );

		// sanitize_title() will reject leading slashes; underscores survive
		// sanitization but fail the [a-z0-9-]+ pattern check.
		$result = $ability->run(
			[
				'slug' => 'has_underscore',
				'name' => 'Bad Slug',
			]
		);

		$this->assertWPError( $result );
		$this->assertSame( 'sd_ai_agent_invalid_slug', $result->get_error_code() );
	}

	/**
	 * ScaffoldBlockThemeAbility returns WP_Error when name is empty.
	 */
	public function test_scaffold_returns_wp_error_for_empty_name(): void {
		$ability = new ScaffoldBlockThemeAbility( 'sd-ai-agent/scaffold-block-theme' );

		$result = $ability->run(
			[
				'slug' => $this->unique_slug( 'noname' ),
				'name' => '   ',
			]
		);

		$this->assertWPError( $result );
		$this->assertSame( 'sd_ai_agent_empty_theme_name', $result->get_error_code() );
	}

	/**
	 * ScaffoldBlockThemeAbility creates the three mandatory files plus the
	 * minimum templates/index.html and returns a well-formed result.
	 */
	public function test_scaffold_creates_block_theme_skeleton(): void {
		$slug    = $this->unique_slug( 'scaffold-happy' );
		$ability = new ScaffoldBlockThemeAbility( 'sd-ai-agent/scaffold-block-theme' );

		$result = $ability->run(
			[
				'slug'        => $slug,
				'name'        => 'Scaffold Happy',
				'description' => 'Generated by ThemeBuilderAbilitiesTest.',
				'author'      => 'AI Agent',
			]
		);

		$this->assertIsArray( $result );
		$this->assertSame( $slug, $result['slug'] );
		$this->assertSame( $slug, $result['stylesheet'] );
		$this->assertFalse( $result['overwritten'] );

		$theme_dir = trailingslashit( get_theme_root() ) . $slug;
		$this->assertDirectoryExists( $theme_dir );
		$this->assertFileExists( $theme_dir . '/theme.json' );
		$this->assertFileExists( $theme_dir . '/style.css' );
		$this->assertFileExists( $theme_dir . '/functions.php' );
		$this->assertFileExists( $theme_dir . '/templates/index.html' );

		// theme.json must be valid JSON.
		$theme_json = json_decode( (string) file_get_contents( $theme_dir . '/theme.json' ), true );
		$this->assertIsArray( $theme_json );
		$this->assertSame( 3, $theme_json['version'] );

		// style.css must carry the canonical Theme Name header so wp_get_theme
		// can detect it.
		$style_css = (string) file_get_contents( $theme_dir . '/style.css' );
		$this->assertStringContainsString( 'Theme Name: Scaffold Happy', $style_css );
		$this->assertStringContainsString( 'Text Domain: ' . $slug, $style_css );

		// functions.php must declare ABSPATH guard and prefixed setup function.
		$functions_php = (string) file_get_contents( $theme_dir . '/functions.php' );
		$this->assertStringContainsString( "if ( ! defined( 'ABSPATH' ) )", $functions_php );
		$prefix = str_replace( '-', '_', $slug );
		$this->assertStringContainsString( "function {$prefix}_setup()", $functions_php );
	}

	/**
	 * ScaffoldBlockThemeAbility refuses to overwrite by default.
	 */
	public function test_scaffold_refuses_to_overwrite_existing_theme(): void {
		$slug    = $this->unique_slug( 'no-overwrite' );
		$ability = new ScaffoldBlockThemeAbility( 'sd-ai-agent/scaffold-block-theme' );

		$first = $ability->run(
			[
				'slug' => $slug,
				'name' => 'First',
			]
		);
		$this->assertIsArray( $first );

		$second = $ability->run(
			[
				'slug' => $slug,
				'name' => 'Second',
			]
		);

		$this->assertWPError( $second );
		$this->assertSame( 'sd_ai_agent_theme_exists', $second->get_error_code() );
	}

	/**
	 * ScaffoldBlockThemeAbility honours the overwrite flag.
	 */
	public function test_scaffold_overwrites_when_flag_set(): void {
		$slug    = $this->unique_slug( 'overwrite-ok' );
		$ability = new ScaffoldBlockThemeAbility( 'sd-ai-agent/scaffold-block-theme' );

		$first = $ability->run(
			[
				'slug' => $slug,
				'name' => 'First',
			]
		);
		$this->assertIsArray( $first );

		$second = $ability->run(
			[
				'slug'      => $slug,
				'name'      => 'Second',
				'overwrite' => true,
			]
		);

		$this->assertIsArray( $second );
		$this->assertTrue( $second['overwritten'] );

		// Confirm the second-write contents replaced the first.
		$style_css = (string) file_get_contents(
			trailingslashit( get_theme_root() ) . $slug . '/style.css'
		);
		$this->assertStringContainsString( 'Theme Name: Second', $style_css );
	}

	/**
	 * Custom theme_json payloads are honoured verbatim.
	 */
	public function test_scaffold_accepts_custom_theme_json(): void {
		$slug    = $this->unique_slug( 'custom-json' );
		$ability = new ScaffoldBlockThemeAbility( 'sd-ai-agent/scaffold-block-theme' );

		$custom = [
			'$schema'  => 'https://schemas.wp.org/trunk/theme.json',
			'version'  => 3,
			'settings' => [
				'color' => [
					'palette' => [
						[
							'slug'  => 'brand',
							'name'  => 'Brand',
							'color' => '#abcdef',
						],
					],
				],
			],
		];

		$result = $ability->run(
			[
				'slug'       => $slug,
				'name'       => 'Custom JSON',
				'theme_json' => $custom,
			]
		);

		$this->assertIsArray( $result );

		$decoded = json_decode(
			(string) file_get_contents( trailingslashit( get_theme_root() ) . $slug . '/theme.json' ),
			true
		);
		$this->assertIsArray( $decoded );
		$this->assertSame( '#abcdef', $decoded['settings']['color']['palette'][0]['color'] );
	}

	/**
	 * ScaffoldBlockThemeAbility resolves `..` segments in WP_CONTENT_DIR
	 * before passing the target path to wp_mkdir_p().
	 *
	 * Regression test for PR #1392 follow-up: dev installs where
	 * WP_CONTENT_DIR is defined with a relative ".." segment (e.g. plugin
	 * worktrees symlinked into the install) caused wp_mkdir_p() to refuse
	 * the create even when the parent themes directory was writable and a
	 * raw mkdir() on the same path succeeded.
	 */
	public function test_scaffold_handles_theme_root_with_parent_dir_segments(): void {
		$canonical = untrailingslashit( get_theme_root() );

		// Simulate a WP_CONTENT_DIR defined with a `..` segment by routing
		// the theme_root filter through "<parent>/<basename>/../<basename>".
		$dirname  = dirname( $canonical );
		$basename = basename( $canonical );
		$bouncy   = $dirname . '/../' . basename( $dirname ) . '/' . $basename;

		$filter = static function () use ( $bouncy ) {
			return $bouncy;
		};
		add_filter( 'theme_root', $filter );

		try {
			$slug    = $this->unique_slug( 'realpath-fix' );
			$ability = new ScaffoldBlockThemeAbility( 'sd-ai-agent/scaffold-block-theme' );

			$result = $ability->run(
				[
					'slug' => $slug,
					'name' => 'Realpath Fix',
				]
			);

			$this->assertIsArray(
				$result,
				is_wp_error( $result )
					? 'Expected scaffold to succeed despite ".." segments in theme_root. Got: ' . $result->get_error_code() . ' / ' . $result->get_error_message()
					: ''
			);

			$canonical_theme_dir = $canonical . '/' . $slug;
			$this->assertDirectoryExists( $canonical_theme_dir );
			$this->assertFileExists( $canonical_theme_dir . '/theme.json' );
		} finally {
			remove_filter( 'theme_root', $filter );
		}
	}

	// ── ActivateThemeAbility ──────────────────────────────────────────────

	/**
	 * ActivateThemeAbility returns WP_Error when stylesheet is missing.
	 */
	public function test_activate_returns_wp_error_for_missing_stylesheet(): void {
		$ability = new ActivateThemeAbility( 'sd-ai-agent/activate-theme' );

		$result = $ability->run( [] );

		$this->assertWPError( $result );
		$this->assertSame( 'sd_ai_agent_invalid_stylesheet', $result->get_error_code() );
	}

	/**
	 * ActivateThemeAbility returns WP_Error when the requested theme does not
	 * exist on disk.
	 */
	public function test_activate_returns_wp_error_for_missing_theme(): void {
		$ability = new ActivateThemeAbility( 'sd-ai-agent/activate-theme' );

		$result = $ability->run( [ 'stylesheet' => 'this-theme-does-not-exist-' . wp_generate_password( 8, false ) ] );

		$this->assertWPError( $result );
		$this->assertSame( 'sd_ai_agent_theme_not_found', $result->get_error_code() );
	}

	/**
	 * ActivateThemeAbility returns WP_Error when the theme declares a
	 * WordPress version requirement that exceeds the running core version
	 * (GH#1508). The stylesheet option must remain unchanged.
	 */
	public function test_activate_returns_wp_error_when_wp_version_requirement_unmet(): void {
		$slug = $this->unique_slug( 'req-wp' );
		$this->stage_minimal_theme( $slug, '99.9.9', '' );
		wp_clean_themes_cache();

		$ability  = new ActivateThemeAbility( 'sd-ai-agent/activate-theme' );
		$previous = (string) get_stylesheet();

		$result = $ability->run( [ 'stylesheet' => $slug ] );

		$this->assertWPError( $result );
		$this->assertSame( 'sd_ai_agent_theme_requirements_unmet', $result->get_error_code() );
		$this->assertSame(
			$previous,
			(string) get_stylesheet(),
			'stylesheet option must not change when WP version requirement is unmet'
		);
	}

	/**
	 * ActivateThemeAbility returns WP_Error when the theme declares a PHP
	 * version requirement that exceeds the running PHP version (GH#1508).
	 * The stylesheet option must remain unchanged.
	 */
	public function test_activate_returns_wp_error_when_php_version_requirement_unmet(): void {
		$slug = $this->unique_slug( 'req-php' );
		$this->stage_minimal_theme( $slug, '', '99.9.9' );
		wp_clean_themes_cache();

		$ability  = new ActivateThemeAbility( 'sd-ai-agent/activate-theme' );
		$previous = (string) get_stylesheet();

		$result = $ability->run( [ 'stylesheet' => $slug ] );

		$this->assertWPError( $result );
		$this->assertSame( 'sd_ai_agent_theme_requirements_unmet', $result->get_error_code() );
		$this->assertSame(
			$previous,
			(string) get_stylesheet(),
			'stylesheet option must not change when PHP version requirement is unmet'
		);
	}

	/**
	 * ActivateThemeAbility activates a previously-scaffolded theme and
	 * reports both the previous and the new stylesheet.
	 */
	public function test_activate_switches_to_scaffolded_theme(): void {
		$slug      = $this->unique_slug( 'activate-flow' );
		$scaffold  = new ScaffoldBlockThemeAbility( 'sd-ai-agent/scaffold-block-theme' );
		$activator = new ActivateThemeAbility( 'sd-ai-agent/activate-theme' );

		$built = $scaffold->run(
			[
				'slug' => $slug,
				'name' => 'Activate Flow',
			]
		);
		$this->assertIsArray( $built );

		// wp_get_theme caches WP_Theme objects on the themes directory listing;
		// force a refresh so the just-created theme is visible.
		wp_clean_themes_cache();

		$previous = (string) get_stylesheet();
		$result   = $activator->run( [ 'stylesheet' => $slug ] );

		$this->assertIsArray( $result );
		$this->assertSame( $previous, $result['previous_stylesheet'] );
		$this->assertSame( $slug, $result['stylesheet'] );
		$this->assertSame( $slug, get_stylesheet() );
	}

	// ── Helpers ───────────────────────────────────────────────────────────

	/**
	 * Generate a unique theme slug for the current test and register it for
	 * cleanup in tearDown.
	 *
	 * @param string $prefix Short identifier embedded in the slug for log clarity.
	 * @return string
	 */
	private function unique_slug( string $prefix ): string {
		$slug                  = 'sd-ai-test-' . $prefix . '-' . strtolower( wp_generate_password( 8, false ) );
		$this->created_slugs[] = $slug;
		return $slug;
	}

	/**
	 * Stage a minimal theme on disk with the given version requirements so
	 * ActivateThemeAbility tests can exercise the requirements-validation path
	 * without going through ScaffoldBlockThemeAbility (GH#1508).
	 *
	 * The slug must already be registered with unique_slug() so tearDown()
	 * removes the directory.
	 *
	 * @param string $slug         Theme directory name / stylesheet slug.
	 * @param string $requires_wp  Value for "Requires at least:" header; '' to omit.
	 * @param string $requires_php Value for "Requires PHP:" header; '' to omit.
	 */
	private function stage_minimal_theme( string $slug, string $requires_wp, string $requires_php ): void {
		$theme_dir = trailingslashit( get_theme_root() ) . $slug;
		wp_mkdir_p( $theme_dir . '/templates' );

		$requires_wp_line  = '' !== $requires_wp  ? "Requires at least: {$requires_wp}\n" : '';
		$requires_php_line = '' !== $requires_php ? "Requires PHP: {$requires_php}\n" : '';

		file_put_contents(
			$theme_dir . '/style.css',
			"/*\n" .
			"Theme Name: Test Requirements {$slug}\n" .
			"Description: Staged by requirements validation test.\n" .
			"Version: 1.0.0\n" .
			$requires_wp_line .
			$requires_php_line .
			'*/'
		);

		// Block themes require templates/index.html to be considered structurally
		// valid by WP_Theme::errors(). Without it the ability returns
		// sd_ai_agent_theme_invalid before reaching validate_theme_requirements().
		file_put_contents( $theme_dir . '/templates/index.html', '<!-- wp:paragraph --><p></p><!-- /wp:paragraph -->' );
	}

	/**
	 * Recursively delete a directory.
	 *
	 * @param string $dir Absolute directory path.
	 */
	private static function rrmdir( string $dir ): void {
		if ( ! is_dir( $dir ) ) {
			return;
		}
		foreach ( scandir( $dir ) ?: [] as $entry ) {
			if ( '.' === $entry || '..' === $entry ) {
				continue;
			}
			$path = $dir . DIRECTORY_SEPARATOR . $entry;
			if ( is_dir( $path ) ) {
				self::rrmdir( $path );
			} else {
				@unlink( $path );
			}
		}
		@rmdir( $dir );
	}
}
