<?php

declare(strict_types=1);
/**
 * Site-wide block and pattern usage inventory.
 *
 * Scans all published posts/pages (capped at POST_SCAN_LIMIT) to tally
 * block usage counts, namespace totals, and synced-pattern references.
 * Results are stored in a site option and refreshed either on-demand
 * (admin button) or via a daily WP-Cron tick (opt-in setting).
 *
 * Adopted from ~/Git/block-mcp/wordpress-plugin/gk-block-api/includes/class-block-inventory.php
 * — uses the same chunked-walk + recursive-tally strategy but is
 * scoped to the four fields required by the sd-ai-agent/get-site-block-usage
 * ability: block_counts, pattern_counts, top_namespaces, last_scanned.
 *
 * @package SdAiAgent\Core
 * @license GPL-2.0-or-later
 * @see     https://github.com/Ultimate-Multisite/superdav-ai-agent/issues/1716
 */

namespace SdAiAgent\Core;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Cached site-wide block + pattern usage inventory.
 *
 * All public entry points are static; instances are not needed since the
 * class has no per-request state. Constants are public so tests and
 * handlers can reference them without hard-coding strings.
 */
class BlockInventory {

	/**
	 * Option key for the persisted inventory result.
	 *
	 * Stores an array with keys: block_counts, pattern_counts,
	 * top_namespaces, last_scanned, truncated, scanned_posts.
	 *
	 * @var string
	 */
	const INVENTORY_OPTION = 'sd_ai_agent_block_inventory';

	/**
	 * Option key tracking the last manual-refresh timestamp (rate-limit).
	 *
	 * @var string
	 */
	const REFRESH_LAST_RUN_OPTION = 'sd_ai_agent_block_inventory_refresh_last';

	/**
	 * WP-Cron hook name for the daily background refresh.
	 *
	 * @var string
	 */
	const CRON_HOOK = 'sd_ai_agent_refresh_block_usage';

	/**
	 * Option key that controls whether the daily cron refresh is enabled.
	 *
	 * Stored within the sd_ai_agent_settings array under the key
	 * 'block_inventory_cron_enabled'. Default: false (opt-in).
	 *
	 * @var string
	 */
	const CRON_ENABLED_SETTING = 'block_inventory_cron_enabled';

	/**
	 * Default TTL (seconds). Filterable via `sd_ai_agent_block_usage_ttl`.
	 *
	 * @var int
	 */
	const DEFAULT_TTL = DAY_IN_SECONDS;

	/**
	 * Maximum published posts to scan per inventory run.
	 *
	 * Caps peak memory and runtime on large sites. Posts are ordered by
	 * date DESC so the most recent content is always included.
	 *
	 * @var int
	 */
	const POST_SCAN_LIMIT = 1000;

	/**
	 * Chunk size for the batched WP_Query walk.
	 *
	 * Keeps peak memory predictable on shared hosting.
	 *
	 * @var int
	 */
	const SCAN_BATCH_SIZE = 200;

	/**
	 * Minimum interval between manual (admin-button) refreshes, in seconds.
	 *
	 * Prevents thrashing: even if the button is clicked repeatedly, a full
	 * scan runs at most once every REFRESH_MIN_INTERVAL seconds.
	 *
	 * @var int
	 */
	const REFRESH_MIN_INTERVAL = HOUR_IN_SECONDS;

	// ── Public API ─────────────────────────────────────────────────────────

	/**
	 * Return the cached inventory, optionally forcing a fresh scan.
	 *
	 * When $refresh is true the result is regenerated by scanning published
	 * content, subject to the manual-refresh rate limit.
	 *
	 * @param bool $refresh Force a fresh scan instead of reading the cache.
	 * @return array<string,mixed> {
	 *     @type array<string,int> $block_counts   block_name => int (total instances).
	 *     @type array<string,int> $pattern_counts pattern_name => int (synced-pattern refs).
	 *     @type array<string,int> $top_namespaces namespace => int, sorted descending.
	 *     @type string            $last_scanned   ISO 8601 timestamp or empty string.
	 *     @type bool              $truncated      True when POST_SCAN_LIMIT was reached.
	 *     @type int               $scanned_posts  Number of posts actually walked.
	 * }
	 */
	public static function get( bool $refresh = false ): array {
		if ( ! $refresh ) {
			$cached = self::get_cached();
			if ( null !== $cached && self::is_fresh( $cached ) ) {
				return $cached;
			}
		}

		// Rate-limit manual refreshes so a rapid series of button clicks
		// does not hammer the database with repeated full scans.
		if ( $refresh ) {
			$last = (int) get_option( self::REFRESH_LAST_RUN_OPTION, 0 );
			if ( $last && ( time() - $last ) < self::REFRESH_MIN_INTERVAL ) {
				// Return whatever is cached (possibly stale) rather than erroring.
				$cached = self::get_cached();
				if ( null !== $cached ) {
					return $cached;
				}
				// No cache at all — accept the cost of a scan below.
			}
		}

		$result = self::build();
		self::persist( $result );

		if ( $refresh ) {
			update_option( self::REFRESH_LAST_RUN_OPTION, time(), false );
		}

		return $result;
	}

	/**
	 * Run the daily cron refresh.
	 *
	 * Called by BlockInventoryHandler on the CRON_HOOK action. Bypasses the
	 * manual rate limit so the scheduled job always runs regardless of when
	 * the button was last clicked.
	 *
	 * @return void
	 */
	public static function run_cron_refresh(): void {
		$result = self::build();
		self::persist( $result );
	}

	/**
	 * Whether the daily cron refresh is enabled (opt-in setting).
	 *
	 * @return bool
	 */
	public static function is_cron_enabled(): bool {
		$settings = get_option( Settings::OPTION_NAME, array() );
		return ! empty( $settings[ self::CRON_ENABLED_SETTING ] );
	}

	/**
	 * Schedule the daily cron event if the setting is on and not yet scheduled.
	 * Safe to call multiple times (idempotent).
	 *
	 * @return void
	 */
	public static function maybe_schedule(): void {
		if ( ! self::is_cron_enabled() ) {
			return;
		}
		if ( ! wp_next_scheduled( self::CRON_HOOK ) ) {
			wp_schedule_event( time() + HOUR_IN_SECONDS, 'daily', self::CRON_HOOK );
		}
	}

	/**
	 * Unschedule the daily cron event (called on deactivation).
	 *
	 * @return void
	 */
	public static function unschedule(): void {
		$timestamp = wp_next_scheduled( self::CRON_HOOK );
		if ( $timestamp ) {
			wp_unschedule_event( $timestamp, self::CRON_HOOK );
		}
	}

	/**
	 * Clear the persisted inventory (useful after uninstall).
	 *
	 * @return void
	 */
	public static function delete_cache(): void {
		delete_option( self::INVENTORY_OPTION );
		delete_option( self::REFRESH_LAST_RUN_OPTION );
	}

	// ── Internal scan ──────────────────────────────────────────────────────

	/**
	 * Walk all published posts and build a fresh inventory result.
	 *
	 * Capped at POST_SCAN_LIMIT posts ordered by date DESC. If more posts
	 * exist the `truncated` flag is set in the returned array.
	 *
	 * @return array<string,mixed> Structured inventory with block_counts, pattern_counts,
	 *                              top_namespaces, last_scanned, truncated, scanned_posts.
	 */
	public static function build(): array {
		/** @var array<string,int> $block_counts */
		$block_counts = array();
		/** @var array<string,int> $namespace_totals */
		$namespace_totals = array();
		$pattern_refs     = array();
		$scanned_posts    = 0;
		$truncated        = false;

		$post_types = array_values( get_post_types( array( 'public' => true ), 'names' ) );
		$paged      = 1;

		do {
			$offset = ( $paged - 1 ) * self::SCAN_BATCH_SIZE;

			// Stop early once POST_SCAN_LIMIT has been reached.
			if ( $scanned_posts >= self::POST_SCAN_LIMIT ) {
				$truncated = true;
				break;
			}

			// Remaining budget for this batch.
			$remaining_budget = self::POST_SCAN_LIMIT - $scanned_posts;
			$per_page         = min( self::SCAN_BATCH_SIZE, $remaining_budget );

			$batch = get_posts(
				array(
					'post_type'           => $post_types,
					'post_status'         => 'publish',
					'posts_per_page'      => $per_page,
					'paged'               => $paged,
					'fields'              => 'ids',
					'no_found_rows'       => true,
					'orderby'             => 'date',
					'order'               => 'DESC',
					'ignore_sticky_posts' => true,
				)
			);

			$batch_size = count( $batch );

			foreach ( $batch as $post_id ) {
				$raw     = get_post_field( 'post_content', (int) $post_id, 'raw' );
				$content = is_string( $raw ) ? $raw : '';
				if ( '' === $content || ! has_blocks( $content ) ) {
					continue;
				}
				$blocks = parse_blocks( $content );
				if ( ! is_array( $blocks ) ) {
					continue;
				}
				self::count_blocks_recursive( $blocks, $block_counts, $namespace_totals, $pattern_refs );
				++$scanned_posts;
			}

			// Flush per-request object cache to bound memory growth.
			if ( function_exists( 'wp_cache_flush_runtime' ) ) {
				wp_cache_flush_runtime();
			}

			// Detect whether more posts exist beyond this batch.
			if ( $batch_size === $per_page && $scanned_posts < self::POST_SCAN_LIMIT ) {
				// Check if we'd still have more posts.
				if ( $batch_size < $per_page ) {
					// Fewer results than requested — no more pages.
					break;
				}
			}

			++$paged;
		} while ( $batch_size >= $per_page && $scanned_posts < self::POST_SCAN_LIMIT );

		// Detect truncation: if we stopped because we hit POST_SCAN_LIMIT,
		// check if further posts exist. We do a lightweight count query.
		if ( ! $truncated && $scanned_posts >= self::POST_SCAN_LIMIT ) {
			$extra     = get_posts(
				array(
					'post_type'           => $post_types,
					'post_status'         => 'publish',
					'posts_per_page'      => 1,
					'offset'              => self::POST_SCAN_LIMIT,
					'fields'              => 'ids',
					'no_found_rows'       => true,
					'orderby'             => 'date',
					'order'               => 'DESC',
					'ignore_sticky_posts' => true,
				)
			);
			$truncated = ! empty( $extra );
		}

		// Sort block counts descending by usage.
		arsort( $block_counts );

		// Sort namespace totals descending.
		arsort( $namespace_totals );

		// Resolve synced-pattern IDs to names.
		$pattern_counts = self::resolve_pattern_refs( $pattern_refs );

		return array(
			'block_counts'   => $block_counts,
			'pattern_counts' => $pattern_counts,
			'top_namespaces' => $namespace_totals,
			'last_scanned'   => gmdate( 'c' ),
			'truncated'      => $truncated,
			'scanned_posts'  => $scanned_posts,
		);
	}

	/**
	 * Recursively tally blocks in a parse_blocks() result.
	 *
	 * Increments block_counts and namespace_totals for each named block.
	 * Tracks synced-pattern references (core/block with a `ref` attribute).
	 *
	 * @param array<int|string,mixed> $blocks           parse_blocks() output.
	 * @param array<string,int>       &$block_counts    Running total: block_name => int.
	 * @param array<string,int>       &$namespace_totals Running total: namespace => int.
	 * @param array<int,int>          &$pattern_refs    Running total: pattern_id (int) => int.
	 * @return void
	 */
	private static function count_blocks_recursive(
		array $blocks,
		array &$block_counts,
		array &$namespace_totals,
		array &$pattern_refs
	): void {
		foreach ( $blocks as $block ) {
			if ( ! is_array( $block ) ) {
				continue;
			}
			$name = isset( $block['blockName'] ) && is_string( $block['blockName'] ) ? $block['blockName'] : '';

			if ( '' === $name ) {
				// Freeform / whitespace — skip but still recurse into inner blocks.
				if ( ! empty( $block['innerBlocks'] ) && is_array( $block['innerBlocks'] ) ) {
					self::count_blocks_recursive( $block['innerBlocks'], $block_counts, $namespace_totals, $pattern_refs );
				}
				continue;
			}

			// Block count.
			$block_counts[ $name ] = ( $block_counts[ $name ] ?? 0 ) + 1;

			// Namespace total.
			$slash_pos               = strpos( $name, '/' );
			$ns                      = false !== $slash_pos ? substr( $name, 0, $slash_pos ) : $name;
			$namespace_totals[ $ns ] = ( $namespace_totals[ $ns ] ?? 0 ) + 1;

			// Synced pattern references (core/block with ref attribute).
			if ( 'core/block' === $name && isset( $block['attrs']['ref'] ) ) {
				$ref_id                  = (int) $block['attrs']['ref'];
				$pattern_refs[ $ref_id ] = ( $pattern_refs[ $ref_id ] ?? 0 ) + 1;
			}

			// Recurse into inner blocks.
			if ( ! empty( $block['innerBlocks'] ) && is_array( $block['innerBlocks'] ) ) {
				self::count_blocks_recursive( $block['innerBlocks'], $block_counts, $namespace_totals, $pattern_refs );
			}
		}
	}

	/**
	 * Resolve synced-pattern post IDs to titles with ref counts.
	 *
	 * Also scans registered block patterns (non-synced) to include their
	 * names if referenced by slug via core/pattern blocks.
	 *
	 * @param array<int,int> $pattern_refs Pattern post ID => int (ref count).
	 * @return array<string,int> pattern_name => int (sorted descending by refs).
	 */
	private static function resolve_pattern_refs( array $pattern_refs ): array {
		/** @var array<string,int> $resolved */
		$resolved = array();

		foreach ( $pattern_refs as $pattern_id => $count ) {
			$post = get_post( $pattern_id );
			if ( $post && 'wp_block' === $post->post_type ) {
				$resolved[ $post->post_title ] = ( $resolved[ $post->post_title ] ?? 0 ) + $count;
			} else {
				// Deleted/missing pattern — use placeholder.
				$placeholder              = sprintf( '(deleted pattern #%d)', $pattern_id );
				$resolved[ $placeholder ] = ( $resolved[ $placeholder ] ?? 0 ) + $count;
			}
		}

		// Include registered (PHP/theme) patterns referenced in content.
		// core/pattern blocks use a `slug` attribute instead of `ref`.
		// These are counted separately in block_counts (as core/pattern) but
		// we expose pattern_counts keyed by name for convenience.
		// No additional processing needed here — caller can cross-reference
		// core/pattern entries in block_counts if slug-level detail is needed.

		arsort( $resolved );
		return $resolved;
	}

	// ── Cache helpers ──────────────────────────────────────────────────────

	/**
	 * Read the persisted inventory from the site option.
	 *
	 * @return array<string,mixed>|null Persisted inventory array, or null if not set.
	 */
	private static function get_cached(): ?array {
		$raw = get_option( self::INVENTORY_OPTION, null );
		if ( ! is_array( $raw ) ) {
			return null;
		}
		/** @var array<string,mixed> $raw */
		return $raw;
	}

	/**
	 * Whether a cached inventory is still within the TTL window.
	 *
	 * @param array<string,mixed> $cached Previously persisted inventory.
	 * @return bool True when fresh enough to return without re-scanning.
	 */
	private static function is_fresh( array $cached ): bool {
		if ( empty( $cached['last_scanned'] ) ) {
			return false;
		}
		$scanned_ts = strtotime( $cached['last_scanned'] );
		if ( false === $scanned_ts ) {
			return false;
		}
		/**
		 * Filter the block-inventory cache TTL in seconds.
		 *
		 * Return a lower value to get more frequent automatic refreshes,
		 * or a higher value to reduce scan frequency on large sites.
		 * Default: 86400 (24 hours).
		 *
		 * @param int $ttl Cache lifetime in seconds. Default DAY_IN_SECONDS.
		 */
		$ttl = (int) apply_filters( 'sd_ai_agent_block_usage_ttl', self::DEFAULT_TTL );
		return ( time() - $scanned_ts ) < $ttl;
	}

	/**
	 * Persist the inventory result to the site option.
	 *
	 * Autoload=false: the option is large and should only be loaded on
	 * demand (e.g. when the ability is invoked or the admin page is loaded).
	 *
	 * @param array<string,mixed> $result Inventory data to persist.
	 * @return void
	 */
	private static function persist( array $result ): void {
		update_option( self::INVENTORY_OPTION, $result, false );
	}
}
